- hosts: all
  gather_facts: no
  #no_log: True
  tasks:
  - block:
    - shell: (timeout 1 bash -c '</dev/tcp/{{ item }}/22 && echo PORT OPEN || echo PORT CLOSED') 2>/dev/null
      with_items: "{{ ansible_play_batch }}"
      delegate_to: localhost
      failed_when: false
      register: telnet
      run_once: true
    - add_host:
        host: "{{ item.item }}"
        ansible_user: 
        ansible_ssh_private_key_file:
        groups: linux
      when: item.rc == 0
      with_items: "{{ telnet.results }}"
      delegate_to: localhost
      run_once: true
    - add_host:
        host: "{{ item.item }}"
        ansible_user: 
        ansible_port: '5986'
        ansible_password: 
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_read_timeout_sec: 300
        ansible_winrm_operation_timeout_sec: 200
        ansible_become: false
        groups: win
      when: item.rc != 0
      with_items: "{{ telnet.results }}"
      delegate_to: localhost
      run_once: true

- hosts: linux
  become: true
  strategy: free
  roles:
  - linux_agent

- hosts: win
  become: true
  strategy: free
  roles:
  - win_agent

- name: sending agent installation report thorugh mail
  hosts: localhost
  tasks:
  - name: Agent installation report
    mail:
      host: 127.0.0.1
      port: 25
      subject: Agent installation report for Non-Prod Non I&O
      body: "This is auto generated report for Agents installation."
      attach:
        - /home/schopra1/installation_report.csv
        - /home/schopra1/failed_installation_report.csv
      from: stuti.chopra@biogen.com
      to: Stuti <stuti.chopra@biogen.com>
