- hosts: all
  gather_facts: no
  #no_log: True
  tasks:
  - block:
    - shell: nc -zv {{ item }} 22
      with_items: "{{ ansible_play_batch }}"
      delegate_to: localhost
      failed_when: false
      register: telnet
      run_once: true
    - add_host:
        host: "{{ item.item }}"
        ansible_user: schopra1
        ansible_ssh_private_key_file: 
        groups: linux
      when: item.rc == 0
      with_items: "{{ telnet.results }}"
      delegate_to: localhost
      run_once: true
    - add_host:
        host: "{{ item.item }}"
        ansible_user: schopra1
        ansible_port: '5986'
        ansible_password: 
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_read_timeout_sec: 300
        ansible_winrm_operation_timeout_sec: 200
        ansible_become: false
        groups: win
      when: item.rc != 0
      with_items: "{{ telnet.results }}"
      delegate_to: localhost
      run_once: true

- hosts: linux
  become: true
  strategy: free
  tasks:
  - block:
    - name: Checking port 8089 linux
      wait_for:
        host: 10.240.17.51
        port: 8089
        timeout: 30
    - name: Checking port 9997 linux
      wait_for:
        host: 10.240.17.54
        port: 9997
        timeout: 30
        #state: present

- hosts: win
  become: true
  strategy: free
  tasks:
  - block:
    - name: Checking port 9997 windows
      win_wait_for:
        host: 10.240.17.51
        port: 8089
        timeout: 30
  
    - name: Checking port 9997 windows
      win_wait_for:
        host: 10.240.17.54
        port: 9997
        timeout: 30        

