---
# tasks file for win_agent
- name: Checking whether Splunk is installed or not
  win_service:
    name: SplunkForwarder
  register: splunk_stat
  ignore_errors: true

- name: Checking whether Splunk is installed or not
  win_command: splunk.exe status
  args:
    chdir: C:\Program Files\SplunkUniversalForwarder\bin\
  register: splunk_status
  ignore_errors: true
  when: splunk_stat.exists == True

- name: Checking whether Tenable is installed or not
  win_service:
    name: Tenable Nessus Agent
  register: tenable_stat
  ignore_errors: true

- debug: var=splunk_stat

- name: Checking whether Splunk is installed or not
  win_command: nessuscli agent status
  args:
    chdir: C:\Program Files\Tenable\Nessus Agent\
  register: nessus_status
  ignore_errors: true
  when: tenable_stat.exists == True

- name: Checking if service exists
  win_service: 
    name: CSFalconService
  register: falcon_info
  ignore_errors: true

- name: Creating CSV
  file:
    path: '/home/schopra1/splunk_status/splunk_status.csv'
    state: touch
  become: true
  delegate_to: localhost
  changed_when: True
  run_once: True

- name: Setting heading for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/splunk_status.csv'
    line: 'IP_ADDRESS,O.S.,INSTALLATION_STATUS,CONNECTION_TO_MGMT_SERVER'
    regexp: "^IP_ADDRESS"
  become: true
  delegate_to: localhost
  changed_when: True
  run_once: True

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/splunk_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Installed and Linked,{{ splunk_status.stdout_lines }}"
  when: splunk_stat.exists == True and splunk_status.rc == 0
  become: true
  delegate_to: localhost

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/splunk_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Installed but not Linked,Agent not linked"
  when: splunk_stat.exists == True  and splunk_status.rc != 0
  become: true
  delegate_to: localhost

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/splunk_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Not Installed,NA"
  when: splunk_stat.exists == False
  become: true
  delegate_to: localhost

- name: Creating CSV
  file:
    path: '/home/schopra1/splunk_status/tenable_status.csv'
    state: touch
  become: true
  delegate_to: localhost
  changed_when: True
  run_once: True

- name: Setting heading for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/tenable_status.csv'
    line: 'IP_ADDRESS,O.S.,INSTALLATION_STATUS,CONNECTION_TO_MGMT_SERVER'
    regexp: "^IP_ADDRESS"
  become: true
  delegate_to: localhost
  changed_when: True
  run_once: True

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/tenable_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Installed and Linked,{{ nessus_status.stdout_lines[0] }}"
  when: tenable_stat.exists == True and nessus_status.rc == 0
  become: true
  delegate_to: localhost

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/tenable_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Installed but not Linked,{{ nessus_status.stdout_lines[0] }}"
  when: tenable_stat.exists == True and nessus_status.rc != 0
  become: true
  delegate_to: localhost

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/tenable_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Not Installed,NA"
  when: tenable_stat.exists == False
  become: true
  delegate_to: localhost

- name: Creating CSV
  file:
    path: '/home/schopra1/splunk_status/crowdstrike_status.csv'
    state: touch
  become: true
  delegate_to: localhost
  changed_when: True
  run_once: True

- name: Setting heading for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/crowdstrike_status.csv'
    line: 'IP_ADDRESS,O.S.,INSTALLATION_STATUS'
    regexp: "^IP_ADDRESS"
  become: true
  delegate_to: localhost
  changed_when: True
  run_once: True

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/crowdstrike_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Installed and Linked"
  when: falcon_info.exists == True
  become: true
  delegate_to: localhost

- name: entry for CSV
  lineinfile:
    path: '/home/schopra1/splunk_status/crowdstrike_status.csv'
    line: "{{ ansible_facts.ip_addresses[0] }},{{ ansible_distribution }},Not Installed"
  when: falcon_info.exists == False
  become: true
  delegate_to: localhost
