---
# tasks file for linux_agent

#- name: Creating CSV
#  copy:
#    dest: '/home/schopra1/installation_report.csv'
#    content: 'IP_ADDRESS,HOSTNAME,O.S.,AGENT,VERSION,INSTALLATION_STATUS,CONNECTION_TO_MGMT_SERVER,PORT,DATE,TIME'
#  delegate_to: localhost
#  changed_when: True
#  run_once: True

#- name: Creating CSV
#  copy:
#    dest: '/home/schopra1/failed_installation_report.csv'
#    content: 'IP_ADDRESS,HOSTNAME,O.S.,AGENT,VERSION,INSTALLATION_STATUS,CONNECTION_TO_MGMT_SERVER,PORT,DATE,TIME'
#  delegate_to: localhost
#  changed_when: True
#  run_once: True

- debug: var=ansible_distribution
- debug: var=ansible_distribution_major_version

- include: amazon.yml
  when: ansible_distribution == 'Amazon'

- include: rhel7.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == "7" or ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"

- include: rhel6.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == "6" or ansible_distribution == 'CentOS' and ansible_distribution_major_version == "6"

- include: oracle7.yml
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "7"

- include: oracle6.yml
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "6"
#- include: rollback.yml
